enhance_resume_initial:
  description: >
    Given the actionable feedback, act on them and improve the {resume}.
  expected_output: >
    An improved version of the {resume} that incorporates ATS feedback and is
    optimized for recruiter engagement.
  agent: resume_enhancer_initial

enhance_resume_final:
  description: >
    Given the  {resume} from resume_enhancer_initial, improve it further to make it more compelling and engaging.
  expected_output: >
    An enhanced version of the {resume} that incorporates ATS feedback and is
    optimized for recruiter engagement.
  agent: resume_enhancer_final
  output_file: output/enhanced_resume_final.pdf
